### ISSUE TITLE
[Bug]: Plugin fails to load with Loupedeck 5.2 and 5.2.1

### ISSUE THREAD

**Issue by LrdGrmRpr** [XeroxDev/Loupedeck-plugin-StreamerBot#5]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.

### Current Behavior

After update to either Loupedeck software 5.2 or 5.2.1, the plugin fails to start. After Loupedeck is open, none of the actions show up and after a little while an error message appears. Clicking on "More info" opens Windows File Exporer, no information. 

### Expected Behavior

Plugin loads normally when Loupedeck is started and Streamer.bot is running.

### Steps To Reproduce

1. Have Streamer.bot plugin installed from Marketplace
2. Update Loupedeck software on Windows to 5.2.1 or 5.2
3. Start Streamer.bot (latest version)
4. Start Loupedeck
5. Go to Streamer.bot plugin section and see possible actions
6. Error message appears, stating that the plugin failed to load

**Comment by XeroxDev** [comment]
Hello and thank you for the feedback.

I'll look into it as soon as I've the time to.

**Comment by LrdGrmRpr** [comment]
I did some debugging on this, and I noticed that the legacy plugin DLL was still in the system. I removed it and afterwards the plugin fails to work on 5.1 as well. So the information above is misleading in a way, the reason this wasn't shown earlier was because of the old DLL actually working in 5.1, but not in 5.2 and up.

The issue however remains and reinstalling the plugin or updating any related software piece does not solve it.

**Comment by LrdGrmRpr** [comment]
I will close this issue as this is caused by legacy plugins. The one killing the plugin was the legacy websocket-sharp.dll plugin that was used previously with the integration. This is not mentioned in the logs, but after removing it the plugin works as intended.

Sorry for the wasted time on this.

**Comment by LrdGrmRpr** [comment]
After working with the plugin for 5 minutes, it crashed as it did before. I will do a clean installation and see if there is anything else clogging the system that would cause this.

**Comment by LrdGrmRpr** [comment]
Cleaned up and now works as intended.

**Comment by XeroxDev** [comment]
Thank you very much for the information and the help! I hope you are having a great day!
